[default]
agent_system_messages_path_general=prompts/agent_system_message_general.json

[hf]
hf_token=hf_***
hf_news=fahadh4ilyas/indonesian_news_datasets

[llm]
base_url=http://10.12.1.35:8585/v1
api_key=pr-***
model=Qwen3-4B